---
abstract: 'Contains Mapper, Combiner and Reducer roles to simplify writing Hadoop Streaming jobs'
author:
  - 'andrew grangaard <spazm@cpan.org>'
  - 'Naoya Ito <naoya@hatena.ne.jp>'
build_requires:
  FindBin: '0'
  Test::Command: '0'
  Test::More: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.022, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Hadoop-Streaming
requires:
  IO::Handle: '0'
  Moo: '0'
  Moo::Role: '0'
  Params::Validate: '0'
  Safe::Isa: '0'
resources:
  repository: git://github.com/spazm/hadoop-streaming-frontend
version: '0.143060'
