---
abstract: 'Contains Mapper, Combiner and Reducer roles to simplify writing Hadoop Streaming jobs'
author:
  - 'andrew grangaard <spazm@cpan.org>'
  - 'Naoya Ito <naoya@hatena.ne.jp>'
build_requires:
  Config: 0
  FindBin: 0
  Moose: 0
  Test::Command: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hadoop-Streaming
requires:
  Any::Moose: 0
  IO::Handle: 0
  Params::Validate: 0
resources:
  repository: http://github.com/spazm/hadoop-streaming-frontend.git
version: 0.122420
